name: DOCKERHUB Get
description: Get DOCKERHUB environment variables
author: a3.services
branding:
  icon: settings
  color: purple
inputs:
  summary:
    description: 'Enable or disable the summary output'
    required: false
    default: 'false'
outputs: {}
runs:
  using: composite
  steps:
    - name: Download environment variables
      uses: actions/download-artifact@v4
      with:
        name: dockerhub-env

    - name: Set DOCKERHUB environment variables
      shell: sh
      run: |
        cat dockerhub.env >> ${GITHUB_ENV}
      
    - name: Summary
      shell: sh
      if: ${{ inputs.summary == 'true' }}
      run: |
        echo "### DOCKERHUB Environment Variables" >> $GITHUB_STEP_SUMMARY
        echo "| Variable           | Value              |" >> $GITHUB_STEP_SUMMARY
        echo "|--------------------|--------------------|" >> $GITHUB_STEP_SUMMARY
        while IFS='=' read -r key value; do
          echo "| $key | $value |" >> $GITHUB_STEP_SUMMARY
        done < dockerhub.env
