name: DOCKERHUB Set
description: Set DOCKERHUB environment variables
author: a3.services
branding:
  icon: settings
  color: purple
inputs:
  file:
    description: 'Path to DOCKERHUB.md'
    required: false
    default: 'DOCKERHUB.md'
  username:
    description: 'DockerHub username used for authentication.'
    required: true
  token:
    description: 'DockerHub access token for authentication.'
    required: true
outputs: {}
runs:
  using: composite
  steps:
    - name: Set DOCKERHUB credentials
      shell: sh
      run: |
        echo "DOCKERHUB_USERNAME=${{ inputs.username }}" >> dockerhub.env
        echo "DOCKERHUB_TOKEN=${{ inputs.token }}" >> dockerhub.env
        
    - name: Extract metadata from DOCKERHUB.md
      shell: sh
      run: |
        echo ".......................................xxxxxxxxxxx"
        cat ${GITHUB_ENV}
        echo "......................................."
        cat dockerhub.env
        echo "......................................."

        # Extrahovanie metadát medzi blokmi ---
        awk 'BEGIN {inside=0} 
             /^---$/ {inside++; next} 
             inside==1 { 
               # Pre každú riadok v metadátach vytvoríme premennú
               if ($1 != "") { 
                 # Hľadáme pozíciu ":" a odtiaľ získavame hodnotu
                 key=$1
                 value=substr($0, index($0, ":") + 1)
                 # Odstránime vedúce a koncové medzery z hodnoty
                 gsub(/^ +| +$/, "", value)
                 # Vytvoríme premennú s prefixom DOCKERHUB_
                 print "DOCKERHUB_" toupper(key) "=" value
               }
             }' "${{ inputs.file }}" >> ${GITHUB_ENV}

        echo "......................................."
        cat ${GITHUB_ENV}
        echo "......................................."
        cat dockerhub.env
        echo "......................................."
        
    - name: Upload environment variables
      uses: actions/upload-artifact@v4
      with:
        name: dockerhub-env
        path: dockerhub.env
