name: DOCKERHUB Set
description: Set DOCKERHUB environment variables
author: a3.services
branding:
  icon: settings
  color: purple
inputs:
  file:
    description: 'Path to DOCKERHUB.md'
    required: false
    default: 'DOCKERHUB.md'
  username:
    description: 'DockerHub username used for authentication.'
    required: true
  token:
    description: 'DockerHub access token for authentication.'
    required: true
outputs: {}
runs:
  using: composite
  steps:
    - name: Set DOCKERHUB credentials
      shell: sh
      run: |
        echo "DOCKERHUB_USERNAME=${{ inputs.username }}" >> dockerhub.env
        echo "DOCKERHUB_TOKEN=${{ inputs.token }}" >> dockerhub.env
        cat dockerhub.env >> ${GITHUB_ENV}
        
    - name: Extract metadata from DOCKERHUB.md
      shell: sh
      run: |
        awk 'BEGIN {inside=0} 
             /^---$/ {inside++; next} 
             inside==1 {print "DOCKERHUB_" toupper($1) "=" substr($0, index($0, $2))}' "${{ inputs.file }}" > dockerhub.env

        cat dockerhub.env >> ${GITHUB_ENV}

        echo "......................................."
        cat ${GITHUB_ENV}
        echo "......................................."
        cat dockerhub.env
        echo "......................................."
        
    - name: Upload environment variables
      uses: actions/upload-artifact@v4
      with:
        name: dockerhub-env
        path: dockerhub.env
