name: DOCKERHUB Set
description: Set DOCKERHUB environment variables
author: a3.services
branding:
  icon: settings
  color: purple
inputs:
  file:
    description: 'Path to DOCKERHUB.md'
    required: false
    default: 'DOCKERHUB.md'
  username:
    description: 'DockerHub username used for authentication.'
    required: true
  token:
    description: 'DockerHub access token for authentication.'
    required: true
outputs: {}
runs:
  using: composite
  steps:
    - name: Set DOCKERHUB credentials
      shell: sh
      run: |
        echo "DOCKERHUB_USERNAME=${{ inputs.username }}" >> dockerhub.env
        echo "DOCKERHUB_TOKEN=${{ inputs.token }}" >> dockerhub.env
        
    - name: Extract metadata from DOCKERHUB.md
      shell: sh
      run: |
        echo ".......................................xxxxxxxxxxx"
        cat ${GITHUB_ENV}
        echo "......................................."
        cat dockerhub.env
        echo "......................................."
        yq

        # Extrahovanie len metadát medzi '---' (YAML hlavička) a odstránenie '---' z premennej
        metadata=$(awk '/^---$/ {inside=!inside} inside && !/^---$/ {print}' "${{ inputs.file }}")
    
        # Skontrolujeme obsah metadát
        echo "+++++++++++++++++++++++++++++++++++++++"
        echo "$metadata"
        echo "+++++++++++++++++++++++++++++++++++++++"
        
        
        echo "$metadata" | while IFS= read -r line; do
          # Pre každý kľúč a hodnotu vytvoriť riadok vo formáte DOCKERHUB_<key>=<value>
          if [ -n "$line" ]; then
            key=$(echo "$line" | cut -d ':' -f1 | tr -d '[:space:]' | tr '[:lower:]' '[:upper:]')
            value=$(echo "$line" | cut -d ':' -f2- | sed 's/^[[:space:]]*//')
            echo "DOCKERHUB_${key}=${value}" >> dockerhub.env
          fi
        done
        
    
        # Pridáme premenné do GITHUB_ENV
        cat dockerhub.env >> ${GITHUB_ENV}

        echo "......................................."
        cat ${GITHUB_ENV}
        echo "......................................."
        cat dockerhub.env
        echo "......................................."
        
    - name: Upload environment variables
      uses: actions/upload-artifact@v4
      with:
        name: dockerhub-env
        path: dockerhub.env
