name: DOCKERHUB Set
description: Set DOCKERHUB environment variables
author: a3.services
branding:
  icon: settings
  color: purple
inputs:
  file:
    description: 'Path to DOCKERHUB.md'
    required: false
    default: 'DOCKERHUB.md'
outputs: {}
runs:
  using: composite
  steps:
    - name: Extract metadata from DOCKERHUB.md
      shell: sh
      run: |
        awk 'BEGIN {inside=0} 
             /^---$/ {inside++; next} 
             inside==1 {print "DOCKERHUB_" toupper($1) "=" substr($0, index($0, $2))}' "${{ inputs.file }}" > dockerhub.env

        cat dockerhub.env >> ${GITHUB_ENV}

        cat ${GITHUB_ENV}
        cat dockerhub.env
        
    - name: Upload environment variables
      uses: actions/upload-artifact@v4
      with:
        name: dockerhub-env
        path: dockerhub.env
